name: JWebMP Build
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
permissions:
  contents: read
  packages: write
jobs:
  BOM:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'BOM/'
      name: 'BOM'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Parent:
    needs:
      - BOM
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: 'Parent/'
      name: 'Parent'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Client:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Parent
    with:
      baseDir: 'Client/'
      name: 'Client'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  TestLibrary:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Parent
    with:
      baseDir: 'Test-Library/'
      name: 'Test-Library'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Servlets:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Client
    with:
      baseDir: 'Servlets/'
      name: 'Servlets'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Core:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    needs:
      - Client
    with:
      baseDir: 'Core/'
      name: 'Core'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
